name:                ron-hs
version:             0.1.0.0
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"
synopsis:            RON format implementation in haskell

library:
  source-dirs:         src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall -Wcompat
  - -Werror=incomplete-patterns
  dependencies:
  - base
  - attoparsec
  - containers
  - hashable
  - text
  - vector
  default-extensions:
  - LambdaCase
  - OverloadedStrings
  - MultiWayIf
