name:                ron-hs
version:             0.1.0.0
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"
synopsis:            RON format implementation in haskell

ghc-options:
- -Wall -Wcompat
- -Werror=incomplete-patterns

library:
  source-dirs:         src
  dependencies:
  - base
  - attoparsec
  - containers
  - hashable
  - template-haskell
  - text
  - vector
  - QuickCheck
  default-extensions:
  - LambdaCase
  - OverloadedStrings
  - MultiWayIf
  - BangPatterns

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
    - base
    - ron-hs
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - text
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
