name:                ron-hs
version:             0.1.2
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"
synopsis:            RON format implementation in haskell

ghc-options:
- -Wall -Wcompat
- -Werror=incomplete-patterns

default-extensions:
- LambdaCase
- OverloadedStrings
- MultiWayIf
- BangPatterns

library:
  source-dirs:         src
  dependencies:
  - base
  - attoparsec
  - bytestring
  - containers
  - hashable
  - template-haskell
  - text
  - vector
  - QuickCheck

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
    - base
    - ron-hs
    - QuickCheck
    - bytestring
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
