name:                ron-hs
version:             0.1.3
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"
synopsis:            RON format implementation in haskell

ghc-options:
- -Wall -Wcompat
- -Werror=incomplete-patterns

default-extensions:
- BangPatterns
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TypeOperators

library:
  source-dirs:         src
  dependencies:
  - base
  - attoparsec
  - bytestring
  - containers
  - hashable
  - scientific
  - template-haskell
  - text
  - vector
  - QuickCheck

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
    - base
    - ron-hs
    - QuickCheck
    - bytestring
    - containers
    - optics-core
    - optics-th
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    - vector
    ghc-options:
    - -Wno-all -Wdefault
    - -Wincomplete-patterns -Werror=incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
